#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

TOP=$(unset CDPATH; cd $(dirname $0)/../; pwd)
NODE_INSTALL=${TOP}/node

if [[ ! -d "${NODE_INSTALL}" && -d "${TOP}/build/node" ]]; then
        # Dev/repo layout.
        NODE_INSTALL=${TOP}/build/node
fi

NODE=${NODE_INSTALL}/bin/node

if [[ -z "${SMF_FMRI}" ]]; then
        ${NODE} --abort-on-uncaught-exception ${TOP}/server.js "$@" | ${NODE} ${TOP}/node_modules/.bin/bunyan
else
        ${NODE} --abort-on-uncaught-exception ${TOP}/server.js "$@"
fi
